// =============================================================================
// NEVR GENERATOR CORE
// Prisma schema and OpenAPI specification generators
// Consolidated from nevr/generator
// =============================================================================

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs"
import { join, dirname } from "path"
import { createHash } from "crypto"
import type { Entity, FieldDef, FieldType, Plugin, Route, EntityAction } from "../types.js"
import { resolveEntity } from "../entity.js"
import { pluralize } from "../router.js"
import { pascalCase } from "../utils/index.js"

// -----------------------------------------------------------------------------
// Cache Types
// -----------------------------------------------------------------------------

interface EntityCache {
  version: string
  entities: Record<string, string> // entityName -> hash
  lastGenerated: string
}

const CACHE_VERSION = "1.0.0"
const CACHE_FILE = ".nevr-cache.json"

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const PRISMA_TYPES: Record<FieldType, string> = {
  string: "String",
  text: "String",
  int: "Int",
  float: "Float",
  boolean: "Boolean",
  datetime: "DateTime",
  json: "Json",
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

function ensureDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
}

function writeFile(path: string, content: string): void {
  ensureDir(dirname(path))
  writeFileSync(path, content, "utf-8")
}

// -----------------------------------------------------------------------------
// Cache Helpers
// -----------------------------------------------------------------------------

/**
 * Generate a hash for an entity's configuration
 */
function hashEntity(entity: Entity): string {
  const data = JSON.stringify({
    name: entity.name,
    config: entity.config,
  })
  return createHash("md5").update(data).digest("hex")
}

/**
 * Load cache from file
 */
function loadCache(outDir: string): EntityCache | null {
  const cachePath = join(outDir, CACHE_FILE)
  if (!existsSync(cachePath)) return null

  try {
    const content = readFileSync(cachePath, "utf-8")
    const cache = JSON.parse(content) as EntityCache
    if (cache.version !== CACHE_VERSION) return null
    return cache
  } catch {
    return null
  }
}

/**
 * Save cache to file
 */
function saveCache(outDir: string, cache: EntityCache): void {
  const cachePath = join(outDir, CACHE_FILE)
  ensureDir(outDir)
  writeFileSync(cachePath, JSON.stringify(cache, null, 2), "utf-8")
}

/**
 * Check which entities have changed since last generation
 */
function getChangedEntities(
  entities: Entity[],
  cache: EntityCache | null
): { changed: Entity[]; unchanged: Entity[]; isFullRebuild: boolean } {
  if (!cache) {
    return { changed: entities, unchanged: [], isFullRebuild: true }
  }

  const changed: Entity[] = []
  const unchanged: Entity[] = []

  for (const entity of entities) {
    const currentHash = hashEntity(entity)
    const cachedHash = cache.entities[entity.name]

    if (cachedHash === currentHash) {
      unchanged.push(entity)
    } else {
      changed.push(entity)
    }
  }

  // Check for removed entities
  const currentNames = new Set(entities.map(e => e.name))
  const removedEntities = Object.keys(cache.entities).filter(name => !currentNames.has(name))

  // If entities were removed, we need a full rebuild
  if (removedEntities.length > 0) {
    return { changed: entities, unchanged: [], isFullRebuild: true }
  }

  return { changed, unchanged, isFullRebuild: false }
}

/**
 * Build new cache from entities
 */
function buildCache(entities: Entity[]): EntityCache {
  const entityHashes: Record<string, string> = {}
  for (const entity of entities) {
    entityHashes[entity.name] = hashEntity(entity)
  }

  return {
    version: CACHE_VERSION,
    entities: entityHashes,
    lastGenerated: new Date().toISOString(),
  }
}

// -----------------------------------------------------------------------------
// Prisma Schema Generator
// -----------------------------------------------------------------------------

/**
 * Generate Prisma schema header (generator + datasource)
 * Used for both single-file and multi-file schema generation
 */
export function generatePrismaHeader(
  options: { provider?: string; splitSchema?: boolean } = {}
): string {
  const { provider = "sqlite", splitSchema = false } = options

  // When using split schema, enable prismaSchemaFolder preview feature
  const previewFeatures = splitSchema ? `\n  previewFeatures = ["prismaSchemaFolder"]` : ""

  return `// =============================================================================
// GENERATED BY NEVR - DO NOT EDIT MANUALLY
// Regenerate with: npx nevr generate
// =============================================================================

generator client {
  provider = "prisma-client-js"${previewFeatures}
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}
`
}

/**
 * Inverse relation info for back-references
 */
interface InverseRelationInfo {
  fromEntity: string
  fieldName: string
  type: string
}

/**
 * Result of building relation maps for schema generation
 */
interface RelationMaps {
  /** Map of entity name to inverse relations pointing at it */
  inverseRelations: Record<string, InverseRelationInfo[]>
  /** Map of entity -> field -> relation name (for disambiguation) */
  relationNames: Record<string, Record<string, string>>
}

/**
 * Build relation maps for inverse relations and relation naming
 * This is used by both single-file and multi-file schema generators
 */
function buildRelationMaps(entities: Entity[]): RelationMaps {
  const inverseRelations: Record<string, InverseRelationInfo[]> = {}
  const relationNames: Record<string, Record<string, string>> = {}

  // First pass: collect all belongsTo relations and create inverse map
  for (const entityDef of entities) {
    const entity = resolveEntity(entityDef)
    const targetCounts: Record<string, string[]> = {}

    for (const [fieldName, field] of Object.entries(entity.config.fields)) {
      if (field.relation?.type === "belongsTo") {
        const relatedEntityOrBuilder = field.relation.entity()
        if (!relatedEntityOrBuilder) continue

        const relatedEntity = resolveEntity(relatedEntityOrBuilder)

        // Track for inverse relation
        if (!inverseRelations[relatedEntity.name]) {
          inverseRelations[relatedEntity.name] = []
        }
        inverseRelations[relatedEntity.name].push({
          fromEntity: entity.name,
          fieldName,
          type: "hasMany"
        })

        // Track for relation naming (disambiguation)
        if (!targetCounts[relatedEntity.name]) {
          targetCounts[relatedEntity.name] = []
        }
        targetCounts[relatedEntity.name].push(fieldName)
      }
    }

    // If multiple relations to same entity, we need relation names
    for (const [target, fields] of Object.entries(targetCounts)) {
      if (fields.length > 1) {
        if (!relationNames[entity.name]) relationNames[entity.name] = {}
        for (const fieldName of fields) {
          relationNames[entity.name][fieldName] = fieldName
        }
      }
    }
  }

  return { inverseRelations, relationNames }
}

/**
 * Generate Prisma models for a set of entities (without header)
 * Used for namespace-specific schema files
 */
export function generatePrismaModels(
  entities: Entity[],
  allEntities: Entity[] // All entities for relation resolution
): string {
  let schema = ""

  // Build relation maps using the shared helper
  const { inverseRelations, relationNames } = buildRelationMaps(allEntities)

  // Generate models only for the specified entities
  for (const entityDef of entities) {
    const entity = resolveEntity(entityDef)
    const modelName = pascalCase(entity.name)

    schema += `\nmodel ${modelName} {\n`
    schema += `  id            String   @id @default(uuid())\n`

    // Regular fields
    for (const [fieldName, field] of Object.entries(entity.config.fields)) {
      if (field.relation?.type === "hasMany") continue
      if (field.relation?.type === "belongsTo") continue

      const prismaType = PRISMA_TYPES[field.type] || "String"
      let line = `  ${fieldName.padEnd(12)} ${prismaType}`

      if (field.optional) line += "?"

      const attrs: string[] = []
      if (field.unique) attrs.push("@unique")
      if (field.default !== undefined) {
        if (typeof field.default === "boolean") {
          attrs.push(`@default(${field.default})`)
        } else if (typeof field.default === "number") {
          attrs.push(`@default(${field.default})`)
        } else if (typeof field.default === "string") {
          attrs.push(`@default("${field.default}")`)
        }
      }

      if (attrs.length > 0) line += " " + attrs.join(" ")
      schema += line + "\n"
    }

    // Timestamps
    if (entity.config.timestamps) {
      schema += `  createdAt     DateTime @default(now())\n`
      schema += `  updatedAt     DateTime @updatedAt\n`
    }

    // Foreign keys and relations
    const foreignKeys: string[] = []

    for (const [fieldName, field] of Object.entries(entity.config.fields)) {
      if (!field.relation) continue

      const relatedEntityOrBuilder = field.relation.entity()
      if (!relatedEntityOrBuilder) continue
      const relatedEntity = resolveEntity(relatedEntityOrBuilder)
      const relatedModel = pascalCase(relatedEntity.name)

      if (field.relation.type === "belongsTo") {
        const fk = field.relation.foreignKey
        foreignKeys.push(fk)

        schema += `  ${fk.padEnd(12)} String${field.optional ? "?" : ""}\n`

        const relName = relationNames[entity.name]?.[fieldName]
        const nameAttr = relName ? `"${relName}", ` : ""
        const onDelete = field.relation.onDelete
          ? `, onDelete: ${pascalCase(field.relation.onDelete)}`
          : ""
        schema += `  ${fieldName.padEnd(12)} ${relatedModel}? @relation(${nameAttr}fields: [${fk}], references: [id]${onDelete})\n`
      } else if (field.relation.type === "hasMany") {
        schema += `  ${fieldName.padEnd(12)} ${relatedModel}[]\n`
      } else if (field.relation.type === "hasOne") {
        schema += `  ${fieldName.padEnd(12)} ${relatedModel}?\n`
      }
    }

    // Inverse relations
    const inverses = inverseRelations[entity.name] || []
    for (const inv of inverses) {
      const fromModel = pascalCase(inv.fromEntity)
      const invFieldName = `${inv.fromEntity}s_${inv.fieldName}`
      const relName = relationNames[inv.fromEntity]?.[inv.fieldName]
      const nameAttr = relName ? `@relation("${relName}")` : ""
      schema += `  ${invFieldName.padEnd(12)} ${fromModel}[] ${nameAttr}\n`
    }

    // Indexes
    if (foreignKeys.length > 0) {
      schema += "\n"
      for (const fk of foreignKeys) {
        schema += `  @@index([${fk}])\n`
      }
    }

    schema += "}\n"
  }

  return schema
}

export function generatePrismaSchema(
  entities: Entity[],
  options: { provider?: string } = {}
): string {
  const { provider = "sqlite" } = options

  let schema = `// =============================================================================
// GENERATED BY NEVR - DO NOT EDIT MANUALLY
// Regenerate with: npx nevr generate
// =============================================================================

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}
`

  // Build relation maps using the shared helper
  const { inverseRelations, relationNames } = buildRelationMaps(entities)

  for (const entityDef of entities) {
    const entity = resolveEntity(entityDef)
    const modelName = pascalCase(entity.name)

    schema += `\nmodel ${modelName} {\n`

    // ID field
    schema += `  id            String   @id @default(uuid())\n`

    // Regular fields
    for (const [fieldName, field] of Object.entries(entity.config.fields)) {
      // Skip hasMany relations (defined on other side)
      if (field.relation?.type === "hasMany") continue

      // Skip belongsTo (we'll add foreign key)
      if (field.relation?.type === "belongsTo") continue

      const prismaType = PRISMA_TYPES[field.type] || "String"
      let line = `  ${fieldName.padEnd(12)} ${prismaType}`

      if (field.optional) line += "?"

      // Add attributes
      const attrs: string[] = []
      if (field.unique) attrs.push("@unique")
      if (field.default !== undefined) {
        if (typeof field.default === "boolean") {
          attrs.push(`@default(${field.default})`)
        } else if (typeof field.default === "number") {
          attrs.push(`@default(${field.default})`)
        } else if (typeof field.default === "string") {
          attrs.push(`@default("${field.default}")`)
        }
      }

      if (attrs.length > 0) {
        line += " " + attrs.join(" ")
      }

      schema += line + "\n"
    }

    // Timestamps
    if (entity.config.timestamps) {
      schema += `  createdAt     DateTime @default(now())\n`
      schema += `  updatedAt     DateTime @updatedAt\n`
    }

    // Foreign keys and relations
    const foreignKeys: string[] = []

    for (const [fieldName, field] of Object.entries(entity.config.fields)) {
      if (!field.relation) continue

      // Resolve the related entity (might be Entity or EntityBuilder)
      const relatedEntityOrBuilder = field.relation.entity()
      if (!relatedEntityOrBuilder) {
        throw new Error(`[Generator] Cannot resolve entity for relation "${fieldName}" in entity "${entity.name}". The entity function returned undefined.`)
      }
      const relatedEntity = resolveEntity(relatedEntityOrBuilder)
      const relatedModel = pascalCase(relatedEntity.name)

      if (field.relation.type === "belongsTo") {
        const fk = field.relation.foreignKey
        foreignKeys.push(fk)

        // Foreign key field
        schema += `  ${fk.padEnd(12)} String${field.optional ? "?" : ""}\n`

        // Relation - add name if multiple relations to same entity
        const relName = relationNames[entity.name]?.[fieldName]
        const nameAttr = relName ? `"${relName}", ` : ""
        const onDelete = field.relation.onDelete
          ? `, onDelete: ${pascalCase(field.relation.onDelete)}`
          : ""
        schema += `  ${fieldName.padEnd(12)} ${relatedModel}? @relation(${nameAttr}fields: [${fk}], references: [id]${onDelete})\n`
      } else if (field.relation.type === "hasMany") {
        schema += `  ${fieldName.padEnd(12)} ${relatedModel}[]\n`
      } else if (field.relation.type === "hasOne") {
        schema += `  ${fieldName.padEnd(12)} ${relatedModel}?\n`
      }
    }

    // Add inverse relations (hasMany back-references)
    const inverses = inverseRelations[entity.name] || []
    for (const inv of inverses) {
      const fromModel = pascalCase(inv.fromEntity)
      const fieldName = `${inv.fromEntity}s_${inv.fieldName}` // e.g. "tasks_assignee"

      // Check if this relation needs a name (because source has multiple relations to this entity)
      const relName = relationNames[inv.fromEntity]?.[inv.fieldName]
      const nameAttr = relName ? `@relation("${relName}")` : ""

      schema += `  ${fieldName.padEnd(12)} ${fromModel}[] ${nameAttr}\n`
    }

    // Indexes for foreign keys
    if (foreignKeys.length > 0) {
      schema += "\n"
      for (const fk of foreignKeys) {
        schema += `  @@index([${fk}])\n`
      }
    }

    schema += "}\n"
  }

  return schema
}

// -----------------------------------------------------------------------------
// Main Generate Function
// -----------------------------------------------------------------------------

export interface GenerateOptions {
  /**
   * Output directory for generated files.
   * For Prisma driver, defaults to "./prisma"
   * Schema will be output as: {outDir}/schema.prisma
   */
  outDir?: string
  /**
   * Database provider for Prisma schema.
   * @default "sqlite"
   */
  prismaProvider?: "sqlite" | "postgresql" | "mysql"
  /**
   * Driver type - determines output folder structure.
   * @default "prisma"
   */
  driver?: "prisma"
  /**
   * Enable schema splitting for large codebases (100+ entities).
   * Uses Prisma's prismaSchemaFolder feature to split schema by namespace.
   * Entities are grouped by their .namespace() setting.
   * @default false (auto-enabled if entities have namespaces)
   */
  splitSchema?: boolean
  /**
   * Enable incremental generation with caching.
   * Only regenerates schema when entities have changed.
   * Stores cache in .nevr-cache.json in the output directory.
   * @default true
   */
  incremental?: boolean
  /**
   * Force full regeneration, ignoring cache.
   * @default false
   */
  force?: boolean
}

export interface GenerateResult {
  files: string[]
  schemaPath: string
  /** When splitSchema is enabled, contains paths to all namespace schema files */
  namespaceFiles?: Record<string, string>
  /** Incremental generation info */
  cache?: {
    wasIncremental: boolean
    changedEntities: string[]
    unchangedEntities: string[]
    skipped: boolean
  }
}

/**
 * Generate database schema from entities.
 *
 * NOTE: Types and API client are no longer generated - they are automatically
 * synced from server to client through NEVR's type inference system.
 *
 * @example
 * ```typescript
 * import { generate } from "nevr/generator"
 * import { user, post } from "./entities"
 *
 * // Generates schema to ./prisma/schema.prisma (default)
 * generate([user, post])
 *
 * // Custom output directory
 * generate([user, post], { outDir: "./db" })
 * ```
 */
export function generate(
  entities: Entity[],
  options: GenerateOptions = {}
): GenerateResult {
  const {
    driver = "prisma",
    prismaProvider = "sqlite",
    incremental = true,
    force = false,
  } = options

  // Default output directory based on driver
  // For prisma driver, output to ./prisma folder (standard convention)
  const outDir = options.outDir || (driver === "prisma" ? "./prisma" : "./generated")

  const files: string[] = []

  // Resolve all entities
  const resolvedEntities = entities.map(resolveEntity)

  // Check if any entities have namespaces
  const hasNamespaces = resolvedEntities.some(e => e.config.namespace)
  const shouldSplit = options.splitSchema ?? hasNamespaces

  console.log("\n🔧 nevr generate\n")

  // Incremental generation with caching
  let cacheInfo: GenerateResult["cache"] = undefined
  if (incremental && !force) {
    const cache = loadCache(outDir)
    const { changed, unchanged, isFullRebuild } = getChangedEntities(resolvedEntities, cache)

    if (changed.length === 0 && !isFullRebuild) {
      console.log(`   ⚡ No changes detected - skipping generation`)
      console.log(`   ${unchanged.length} entities unchanged\n`)

      // Return cached result
      const schemaPath = shouldSplit
        ? join(outDir, "schema", "schema.prisma")
        : join(outDir, "schema.prisma")

      return {
        files: [],
        schemaPath,
        cache: {
          wasIncremental: true,
          changedEntities: [],
          unchangedEntities: unchanged.map(e => e.name),
          skipped: true,
        },
      }
    }

    if (!isFullRebuild && changed.length < resolvedEntities.length) {
      console.log(`   ⚡ Incremental: ${changed.length} changed, ${unchanged.length} unchanged`)
      cacheInfo = {
        wasIncremental: true,
        changedEntities: changed.map(e => e.name),
        unchangedEntities: unchanged.map(e => e.name),
        skipped: false,
      }
    }
  }

  console.log(`   Found ${resolvedEntities.length} entities:`)
  resolvedEntities.forEach(e => {
    const ns = e.config.namespace ? ` (${e.config.namespace})` : ""
    console.log(`   - ${e.name}${ns}`)
  })
  console.log()

  let schemaPath: string
  let namespaceFiles: Record<string, string> | undefined

  if (shouldSplit) {
    // Split schema by namespace
    namespaceFiles = {}

    // Group entities by namespace
    const namespaceMap: Record<string, Entity[]> = { _default: [] }
    for (const entity of resolvedEntities) {
      const ns = entity.config.namespace || "_default"
      if (!namespaceMap[ns]) namespaceMap[ns] = []
      namespaceMap[ns].push(entity)
    }

    const namespaces = Object.keys(namespaceMap).filter(ns => namespaceMap[ns].length > 0)
    console.log(`   📂 Schema splitting enabled (${namespaces.length} namespaces)`)

    // Create schema directory
    const schemaDir = join(outDir, "schema")
    ensureDir(schemaDir)

    // Generate main schema.prisma with header only
    schemaPath = join(schemaDir, "schema.prisma")
    const header = generatePrismaHeader({ provider: prismaProvider, splitSchema: true })
    writeFile(schemaPath, header)
    files.push(schemaPath)
    console.log(`   ✅ ${schemaPath} (config)`)

    // Generate namespace-specific schema files
    for (const ns of namespaces) {
      const nsEntities = namespaceMap[ns]
      const fileName = ns === "_default" ? "models.prisma" : `${ns}.prisma`
      const nsPath = join(schemaDir, fileName)

      const nsHeader = `// =============================================================================
// NAMESPACE: ${ns === "_default" ? "default" : ns}
// Entities: ${nsEntities.map(e => e.name).join(", ")}
// =============================================================================
`
      const models = generatePrismaModels(nsEntities, resolvedEntities)
      writeFile(nsPath, nsHeader + models)
      files.push(nsPath)
      namespaceFiles[ns] = nsPath
      console.log(`   ✅ ${nsPath} (${nsEntities.length} models)`)
    }

    console.log(`
   ℹ️  Schema splitting is enabled using Prisma's prismaSchemaFolder feature.
   All .prisma files in ${schemaDir} are combined into one schema.

   Next steps:
   1. Run: npx prisma db push
   2. Run: npm run dev

   Benefits of schema splitting:
   - Faster schema generation for large codebases
   - Better organization by domain/namespace
   - Parallel team development on different namespaces
`)
  } else {
    // Generate single schema file
    schemaPath = join(outDir, "schema.prisma")
    writeFile(schemaPath, generatePrismaSchema(resolvedEntities, { provider: prismaProvider }))
    files.push(schemaPath)
    console.log(`   ✅ ${schemaPath}`)

    console.log(`
   ℹ️  Types and API client are no longer generated.
   They are automatically synced from server to client.

   Next steps:
   1. Run: npx prisma db push
   2. Run: npm run dev

   💡 Tip: For large codebases (100+ entities), use .namespace() on entities
   to enable schema splitting for better performance.
`)
  }

  // Save cache for incremental generation
  if (incremental) {
    const newCache = buildCache(resolvedEntities)
    saveCache(outDir, newCache)
  }

  return { files, schemaPath, namespaceFiles, cache: cacheInfo }
}

// -----------------------------------------------------------------------------
// Schema-Only Generate (Recommended)
// -----------------------------------------------------------------------------

/**
 * Generate only the database schema.
 * This is the recommended function to use - types and client are auto-synced.
 */
export function generateSchema(
  entities: Entity[],
  options: { outDir?: string; provider?: string } = {}
): { path: string; content: string } {
  const { outDir = "./prisma", provider = "sqlite" } = options

  const resolvedEntities = entities.map(resolveEntity)
  const content = generatePrismaSchema(resolvedEntities, { provider })
  const path = join(outDir, "schema.prisma")

  writeFile(path, content)

  return { path, content }
}

// -----------------------------------------------------------------------------
// OpenAPI 3.0 Generator
// Generates OpenAPI spec from entities using rich metadata
// -----------------------------------------------------------------------------

export interface OpenAPIInfo {
  title: string
  version: string
  description?: string
  contact?: {
    name?: string
    url?: string
    email?: string
  }
  license?: {
    name: string
    url?: string
  }
}

export interface OpenAPIServer {
  url: string
  description?: string
}

export interface OpenAPIGenerateOptions {
  /** API info */
  info: OpenAPIInfo
  /** Server URLs */
  servers?: OpenAPIServer[]
  /** Base path for all routes */
  basePath?: string
  /** Include authentication schemes */
  security?: boolean
  /** Output path (optional - if provided, writes to file) */
  outPath?: string
  /** Plugins to include routes from (e.g., auth, payments) */
  plugins?: Plugin[]
}

export interface OpenAPISpec {
  openapi: "3.0.3"
  info: OpenAPIInfo
  servers?: OpenAPIServer[]
  paths: Record<string, Record<string, unknown>>
  components: {
    schemas: Record<string, unknown>
    securitySchemes?: Record<string, unknown>
  }
  security?: Array<Record<string, string[]>>
  tags: Array<{ name: string; description?: string }>
}

/**
 * Map Nevr field type to OpenAPI schema type
 */
function fieldTypeToOpenAPI(field: FieldDef): Record<string, unknown> {
  const baseType = (): Record<string, unknown> => {
    // If field has enum options, use enum first
    if (field.options && field.options.length > 0) {
      return {
        type: "string",
        enum: field.options,
      }
    }

    switch (field.type) {
      case "string":
      case "text":
        return { type: "string" }
      case "int":
        return { type: "integer" }
      case "float":
        return { type: "number" }
      case "boolean":
        return { type: "boolean" }
      case "datetime":
        return { type: "string", format: "date-time" }
      case "json":
        return { type: "object" }
      default:
        return { type: "string" }
    }
  }

  const result: Record<string, unknown> = baseType()

  // Add metadata from rich metadata
  if (field.meta?.label) {
    result.title = field.meta.label
  }
  if (field.meta?.description) {
    result.description = field.meta.description
  }
  if (field.meta?.example !== undefined) {
    result.example = field.meta.example
  }

  // Add validation constraints
  if (field.min !== undefined) {
    if (field.type === "string" || field.type === "text") {
      result.minLength = field.min
    } else {
      result.minimum = field.min
    }
  }
  if (field.max !== undefined) {
    if (field.type === "string" || field.type === "text") {
      result.maxLength = field.max
    } else {
      result.maximum = field.max
    }
  }

  // Email format
  if (field.isEmail || field.validation?.email) {
    result.format = "email"
  }

  // URL format
  if (field.validation?.url) {
    result.format = "uri"
  }

  // Regex pattern
  if (field.validation?.regex) {
    result.pattern = field.validation.regex.pattern.source
  }

  return result
}

/**
 * Generate OpenAPI schema for an entity
 */
function generateEntitySchema(entity: Entity): Record<string, unknown> {
  const properties: Record<string, unknown> = {
    id: {
      type: "string",
      format: "uuid",
      description: "Unique identifier",
      readOnly: true,
    },
  }

  const required: string[] = ["id"]

  for (const [fieldName, field] of Object.entries(entity.config.fields)) {
    // Skip relation fields in base schema
    if (field.relation) continue

    properties[fieldName] = fieldTypeToOpenAPI(field)

    if (!field.optional && field.default === undefined) {
      required.push(fieldName)
    }
  }

  // Add timestamps
  if (entity.config.timestamps) {
    properties.createdAt = {
      type: "string",
      format: "date-time",
      description: "Creation timestamp",
      readOnly: true,
    }
    properties.updatedAt = {
      type: "string",
      format: "date-time",
      description: "Last update timestamp",
      readOnly: true,
    }
  }

  return {
    type: "object",
    properties,
    required: required.length > 1 ? required : undefined,
  }
}

/**
 * Generate OpenAPI schema for entity creation input
 */
function generateCreateInputSchema(entity: Entity): Record<string, unknown> {
  const properties: Record<string, unknown> = {}
  const required: string[] = []

  for (const [fieldName, field] of Object.entries(entity.config.fields)) {
    // Skip hasMany relations
    if (field.relation?.type === "hasMany") continue

    // For belongsTo, include foreign key
    if (field.relation?.type === "belongsTo") {
      const fk = field.relation.foreignKey
      // Skip owner field (auto-set)
      if (entity.config.ownerField === fk) continue

      properties[fk] = {
        type: "string",
        format: "uuid",
        description: field.meta?.description || `Reference to related ${field.relation.entity().name}`,
      }
      if (!field.optional) {
        required.push(fk)
      }
      continue
    }

    properties[fieldName] = fieldTypeToOpenAPI(field)

    if (!field.optional && field.default === undefined) {
      required.push(fieldName)
    }
  }

  return {
    type: "object",
    properties,
    required: required.length > 0 ? required : undefined,
  }
}

/**
 * Generate OpenAPI schema for entity update input
 */
function generateUpdateInputSchema(entity: Entity): Record<string, unknown> {
  const properties: Record<string, unknown> = {}

  for (const [fieldName, field] of Object.entries(entity.config.fields)) {
    // Skip hasMany relations
    if (field.relation?.type === "hasMany") continue

    // For belongsTo, include foreign key
    if (field.relation?.type === "belongsTo") {
      const fk = field.relation.foreignKey
      // Skip owner field
      if (entity.config.ownerField === fk) continue

      properties[fk] = {
        type: "string",
        format: "uuid",
        description: field.meta?.description || `Reference to related ${field.relation.entity().name}`,
        nullable: true,
      }
      continue
    }

    properties[fieldName] = {
      ...fieldTypeToOpenAPI(field),
      nullable: true,
    }
  }

  return {
    type: "object",
    properties,
  }
}

/**
 * Generate OpenAPI paths for an entity's CRUD operations
 */
function generateEntityPaths(
  entity: Entity,
  basePath: string = ""
): Record<string, Record<string, unknown>> {
  const plural = pluralize(entity.name)
  const modelName = pascalCase(entity.name)
  const paths: Record<string, Record<string, unknown>> = {}

  // Determine if entity needs authentication
  const needsAuth = (op: string): boolean => {
    const rules = entity.config.rules[op as keyof typeof entity.config.rules]
    if (!rules) return false
    return rules.some(r => r !== "everyone")
  }

  const listPath = `${basePath}/${plural}`
  const itemPath = `${basePath}/${plural}/{id}`

  // List endpoint
  paths[listPath] = {
    get: {
      summary: `List all ${plural}`,
      description: `Retrieve a paginated list of ${plural}`,
      operationId: `list${modelName}s`,
      tags: [modelName],
      parameters: [
        {
          name: "limit",
          in: "query",
          description: "Maximum number of items to return",
          schema: { type: "integer", default: 20, maximum: 100 },
        },
        {
          name: "offset",
          in: "query",
          description: "Number of items to skip",
          schema: { type: "integer", default: 0 },
        },
        {
          name: "sort",
          in: "query",
          description: "Sort field (prefix with - for descending)",
          schema: { type: "string" },
        },
      ],
      responses: {
        "200": {
          description: `List of ${plural}`,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  data: {
                    type: "array",
                    items: { $ref: `#/components/schemas/${modelName}` },
                  },
                  pagination: {
                    type: "object",
                    properties: {
                      total: { type: "integer" },
                      limit: { type: "integer" },
                      offset: { type: "integer" },
                    },
                  },
                },
              },
            },
          },
        },
      },
      ...(needsAuth("list") ? { security: [{ bearerAuth: [] }] } : {}),
    },
    post: {
      summary: `Create a new ${entity.name}`,
      description: `Create a new ${entity.name} record`,
      operationId: `create${modelName}`,
      tags: [modelName],
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: { $ref: `#/components/schemas/${modelName}Create` },
          },
        },
      },
      responses: {
        "201": {
          description: `${modelName} created successfully`,
          content: {
            "application/json": {
              schema: { $ref: `#/components/schemas/${modelName}` },
            },
          },
        },
        "400": {
          description: "Validation error",
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
      },
      ...(needsAuth("create") ? { security: [{ bearerAuth: [] }] } : {}),
    },
  }

  // Single item endpoints
  paths[itemPath] = {
    get: {
      summary: `Get a ${entity.name} by ID`,
      description: `Retrieve a single ${entity.name} by its unique identifier`,
      operationId: `get${modelName}`,
      tags: [modelName],
      parameters: [
        {
          name: "id",
          in: "path",
          required: true,
          description: `The ${entity.name} ID`,
          schema: { type: "string", format: "uuid" },
        },
      ],
      responses: {
        "200": {
          description: `${modelName} found`,
          content: {
            "application/json": {
              schema: { $ref: `#/components/schemas/${modelName}` },
            },
          },
        },
        "404": {
          description: `${modelName} not found`,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/Error" },
            },
          },
        },
      },
      ...(needsAuth("read") ? { security: [{ bearerAuth: [] }] } : {}),
    },
    put: {
      summary: `Update a ${entity.name}`,
      description: `Update an existing ${entity.name} by ID`,
      operationId: `update${modelName}`,
      tags: [modelName],
      parameters: [
        {
          name: "id",
          in: "path",
          required: true,
          description: `The ${entity.name} ID`,
          schema: { type: "string", format: "uuid" },
        },
      ],
      requestBody: {
        required: true,
        content: {
          "application/json": {
            schema: { $ref: `#/components/schemas/${modelName}Update` },
          },
        },
      },
      responses: {
        "200": {
          description: `${modelName} updated successfully`,
          content: {
            "application/json": {
              schema: { $ref: `#/components/schemas/${modelName}` },
            },
          },
        },
        "404": {
          description: `${modelName} not found`,
        },
      },
      ...(needsAuth("update") ? { security: [{ bearerAuth: [] }] } : {}),
    },
    delete: {
      summary: `Delete a ${entity.name}`,
      description: `Delete a ${entity.name} by ID`,
      operationId: `delete${modelName}`,
      tags: [modelName],
      parameters: [
        {
          name: "id",
          in: "path",
          required: true,
          description: `The ${entity.name} ID`,
          schema: { type: "string", format: "uuid" },
        },
      ],
      responses: {
        "204": {
          description: `${modelName} deleted successfully`,
        },
        "404": {
          description: `${modelName} not found`,
        },
      },
      ...(needsAuth("delete") ? { security: [{ bearerAuth: [] }] } : {}),
    },
  }

  return paths
}

/**
 * Generate OpenAPI path for an entity action
 */
function generateActionPath(
  entity: Entity,
  actionName: string,
  action: EntityAction,
  basePath: string = ""
): Record<string, Record<string, unknown>> {
  const plural = pluralize(entity.name)
  const modelName = pascalCase(entity.name)
  const paths: Record<string, Record<string, unknown>> = {}

  // Build path based on whether action requires ID
  const pathSuffix = action.path || actionName
  const fullPath = action.requiresId
    ? `${basePath}/${plural}/{id}/${pathSuffix}`
    : `${basePath}/${plural}/${pathSuffix}`

  const method = action.method.toLowerCase()

  // Build request body schema if action has input
  let requestBody: Record<string, unknown> | undefined
  if (action.input && Object.keys(action.input).length > 0) {
    const properties: Record<string, unknown> = {}
    const required: string[] = []

    for (const [fieldName, field] of Object.entries(action.input)) {
      properties[fieldName] = fieldTypeToOpenAPI(field)
      if (!field.optional) {
        required.push(fieldName)
      }
    }

    requestBody = {
      required: true,
      content: {
        "application/json": {
          schema: {
            type: "object",
            properties,
            ...(required.length > 0 ? { required } : {}),
          },
        },
      },
    }
  }

  // Build parameters
  const parameters: Array<Record<string, unknown>> = []
  if (action.requiresId) {
    parameters.push({
      name: "id",
      in: "path",
      required: true,
      description: `The ${entity.name} ID`,
      schema: { type: "string", format: "uuid" },
    })
  }

  // Check if action requires auth
  const needsAuth = action.rules && action.rules.some(r => r !== "everyone")

  // Build extended description with operations info
  let description = action.metadata?.description || `Execute ${actionName} action`

  // Cast to access extended action properties (operations/returns from Entity-First pattern)
  const extAction = action as EntityAction & {
    operations?: Array<{ entity: string; operation: string; data?: unknown }>
    returns?: { entity?: string; pick?: string[]; omit?: string[] }
  }

  // Add operations info if present (Zero API pattern)
  if (extAction.operations && extAction.operations.length > 0) {
    const operationsInfo = extAction.operations.map(op => {
      const opType = op.operation.toUpperCase()
      const dataInfo = op.data === "auto" ? "(auto-mapped from input)" : "(custom data)"
      return `• ${opType} ${op.entity} ${dataInfo}`
    }).join("\n")

    description += `\n\n**Operations:**\n${operationsInfo}`
  }

  // Add returns info if present
  if (extAction.returns) {
    const returnsEntity = extAction.returns.entity || "all results"
    let returnsInfo = `Returns: ${returnsEntity}`
    if (extAction.returns.pick) {
      returnsInfo += ` (fields: ${extAction.returns.pick.join(", ")})`
    }
    if (extAction.returns.omit) {
      returnsInfo += ` (excluding: ${extAction.returns.omit.join(", ")})`
    }
    description += `\n\n**${returnsInfo}**`
  }

  // Build response schema based on returns config
  let responseSchema: Record<string, unknown> = { type: "object" }
  if (extAction.returns?.entity) {
    responseSchema = { $ref: `#/components/schemas/${pascalCase(extAction.returns.entity)}` }
  }

  const operation: Record<string, unknown> = {
    summary: action.metadata?.summary || `${actionName} action on ${entity.name}`,
    description,
    operationId: `${actionName}${modelName}`,
    tags: action.metadata?.tags || [modelName],
    ...(parameters.length > 0 ? { parameters } : {}),
    ...(requestBody ? { requestBody } : {}),
    responses: {
      "200": {
        description: "Action executed successfully",
        content: {
          "application/json": {
            schema: responseSchema,
          },
        },
      },
      "400": {
        description: "Validation error",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
          },
        },
      },
    },
    ...(needsAuth ? { security: [{ bearerAuth: [] }] } : {}),
  }

  paths[fullPath] = { [method]: operation }

  return paths
}

/**
 * Generate OpenAPI path from a plugin route
 */
function generatePluginRoutePath(
  route: Route,
  pluginTag: string
): Record<string, Record<string, unknown>> {
  const paths: Record<string, Record<string, unknown>> = {}
  const method = route.method.toLowerCase()
  const pathPattern = route.path

  // Extract path parameters (e.g., :id -> {id})
  const openApiPath = pathPattern.replace(/:([a-zA-Z0-9_]+)/g, "{$1}")

  // Build parameters from path
  const parameters: Array<Record<string, unknown>> = []
  const paramMatches = pathPattern.match(/:([a-zA-Z0-9_]+)/g)
  if (paramMatches) {
    for (const match of paramMatches) {
      const paramName = match.slice(1) // Remove leading :
      parameters.push({
        name: paramName,
        in: "path",
        required: true,
        schema: { type: "string" },
      })
    }
  }

  // Use route metadata if available
  const meta = route.metadata || {}

  const operation: Record<string, unknown> = {
    summary: meta.summary || `${method.toUpperCase()} ${route.path}`,
    description: meta.description,
    operationId: meta.operationId || `${method}${openApiPath.replace(/[^a-zA-Z0-9]/g, "_")}`,
    tags: meta.tags || [pluginTag],
    ...(parameters.length > 0 ? { parameters } : {}),
    responses: meta.responses || {
      "200": {
        description: "Success",
      },
    },
    ...(meta.requiresAuth ? { security: [{ bearerAuth: [] }] } : {}),
    ...(meta.deprecated ? { deprecated: true } : {}),
  }

  // Add request body for POST/PUT/PATCH
  if (["post", "put", "patch"].includes(method)) {
    if (meta.requestBody) {
      operation.requestBody = meta.requestBody
    } else {
      operation.requestBody = {
        required: true,
        content: {
          "application/json": {
            schema: { type: "object" },
          },
        },
      }
    }
  }

  if (!paths[openApiPath]) {
    paths[openApiPath] = {}
  }
  paths[openApiPath][method] = operation

  return paths
}

/**
 * Generate complete OpenAPI 3.0 specification from entities
 *
 * @example
 * ```typescript
 * import { generateOpenAPI } from "nevr/generator"
 * import { user, post } from "./entities"
 *
 * const spec = generateOpenAPI([user, post], {
 *   info: {
 *     title: "My API",
 *     version: "1.0.0",
 *     description: "API generated by Nevr"
 *   },
 *   servers: [{ url: "http://localhost:3000" }],
 *   outPath: "./docs/openapi.json"
 * })
 * ```
 */
export function generateOpenAPI(
  entities: Entity[],
  options: OpenAPIGenerateOptions
): OpenAPISpec {
  const {
    info,
    servers,
    basePath = "/api",
    security = true,
    outPath,
  } = options

  const resolvedEntities = entities.map(resolveEntity)

  // Build schemas
  const schemas: Record<string, unknown> = {
    Error: {
      type: "object",
      properties: {
        code: {
          type: "string",
          description: "Error code",
          example: "VALIDATION_ERROR",
        },
        message: {
          type: "string",
          description: "Human-readable error message",
        },
        details: {
          type: "array",
          items: {
            type: "object",
            properties: {
              field: { type: "string" },
              message: { type: "string" },
            },
          },
        },
      },
      required: ["code", "message"],
    },
  }

  // Build paths
  let paths: Record<string, Record<string, unknown>> = {}

  // Build tags
  const tags: Array<{ name: string; description?: string }> = []

  for (const entity of resolvedEntities) {
    const modelName = pascalCase(entity.name)

    // Add schemas
    schemas[modelName] = generateEntitySchema(entity)
    schemas[`${modelName}Create`] = generateCreateInputSchema(entity)
    schemas[`${modelName}Update`] = generateUpdateInputSchema(entity)

    // Add paths
    paths = { ...paths, ...generateEntityPaths(entity, basePath) }

    // Add entity action paths
    if (entity.config.actions && Object.keys(entity.config.actions).length > 0) {
      for (const [actionName, action] of Object.entries(entity.config.actions)) {
        const actionPaths = generateActionPath(entity, actionName, action, basePath)
        paths = { ...paths, ...actionPaths }
      }
    }

    // Add tag
    tags.push({
      name: modelName,
      description: `Operations for ${pluralize(entity.name)}`,
    })
  }

  // Add plugin routes
  if (options.plugins && options.plugins.length > 0) {
    for (const plugin of options.plugins) {
      const pluginRoutes = typeof plugin.routes === "function"
        ? [] // Can't resolve without NevrInstance, skip function routes
        : plugin.routes || []

      const pluginTag = plugin.name || plugin.id || "Plugin"
      let hasRoutes = false

      for (const route of pluginRoutes) {
        const routePath = generatePluginRoutePath(route, pluginTag)
        for (const [pathKey, pathOps] of Object.entries(routePath)) {
          if (!paths[pathKey]) {
            paths[pathKey] = {}
          }
          paths[pathKey] = { ...paths[pathKey], ...pathOps }
        }
        hasRoutes = true
      }

      if (hasRoutes) {
        tags.push({
          name: pluginTag,
          description: plugin.description || `${pluginTag} plugin endpoints`,
        })
      }
    }
  }

  // Build spec
  const spec: OpenAPISpec = {
    openapi: "3.0.3",
    info,
    paths,
    components: {
      schemas,
      ...(security
        ? {
          securitySchemes: {
            bearerAuth: {
              type: "http",
              scheme: "bearer",
              bearerFormat: "JWT",
              description: "JWT authentication token",
            },
            cookieAuth: {
              type: "apiKey",
              in: "cookie",
              name: "session",
              description: "Session cookie authentication",
            },
          },
        }
        : {}),
    },
    tags,
  }

  if (servers) {
    spec.servers = servers
  }

  // Write to file if outPath provided
  if (outPath) {
    writeFile(outPath, JSON.stringify(spec, null, 2))
    console.log(`\n✅ OpenAPI spec written to: ${outPath}`)
  }

  return spec
}

