// =============================================================================
// OPENAPI COMMAND
// Generate OpenAPI specification from entities
// =============================================================================

import { writeFileSync } from "fs"
import { join } from "path"
import { loadConfig } from "../utils/config-loader.js"
import {
  extractPluginEntities,
} from "../../generator/plugin-extractor.js"
import type { ConfigPlugin } from "../../config.js"

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface OpenAPICommandOptions {
  /** Custom config file path */
  config?: string
  /** Output file path */
  output?: string
  /** Output format */
  format?: "json" | "yaml"
  /** API title */
  title?: string
  /** API version */
  version?: string
  /** Base path for API */
  basePath?: string
  /** Silent mode */
  silent?: boolean
}

// -----------------------------------------------------------------------------
// OpenAPI Command
// -----------------------------------------------------------------------------

export async function openapiCommand(options: OpenAPICommandOptions = {}): Promise<void> {
  if (!options.silent) {
    console.log("\n⚡ nevr openapi\n")
  }

  try {
    // 1. Load config
    const config = await loadConfig({
      configPath: options.config,
      silent: options.silent,
    })

    // 2. Collect all entities
    const userEntities = config.entities || []
    const plugins = (config.plugins || []) as ConfigPlugin[]
    const pluginEntities = extractPluginEntities(plugins)
    const allEntities = [...userEntities, ...pluginEntities]

    if (allEntities.length === 0) {
      console.log("\n⚠️  No entities found. Add entities to your config first.")
      process.exit(0)
    }

    // 3. Generate OpenAPI spec
    const { generateOpenAPI } = await import("../../generator/core.js")

    const spec = generateOpenAPI(allEntities, {
      info: {
        title: options.title || "Nevr API",
        version: options.version || "1.0.0",
        description: "API generated by Nevr",
      },
      basePath: options.basePath || "/api",
    })

    // 4. Format output
    const format = options.format || "json"
    let content: string

    if (format === "yaml") {
      // Simple YAML conversion (basic, for common use cases)
      content = jsonToYaml(spec)
    } else {
      content = JSON.stringify(spec, null, 2)
    }

    // 5. Write or output
    const outputPath = options.output || `openapi.${format}`

    writeFileSync(join(process.cwd(), outputPath), content)

    if (!options.silent) {
      console.log(`   📄 Entities: ${allEntities.length}`)
      console.log(`   📄 Format: ${format.toUpperCase()}`)
      console.log(`\n✅ Generated ${outputPath}`)
      console.log(`
Next steps:
   • Import into Swagger UI, Postman, or Insomnia
   • Use with OpenAPI generators for client SDKs
   • Host on your API docs page
`)
    }
  } catch (error: any) {
    console.error(`\n❌ OpenAPI generation failed: ${error.message}`)
    if (process.env.DEBUG) {
      console.error(error.stack)
    }
    process.exit(1)
  }
}

// -----------------------------------------------------------------------------
// Simple JSON to YAML converter
// -----------------------------------------------------------------------------

function jsonToYaml(obj: any, indent = 0): string {
  const spaces = "  ".repeat(indent)
  const lines: string[] = []

  if (Array.isArray(obj)) {
    for (const item of obj) {
      if (typeof item === "object" && item !== null) {
        lines.push(`${spaces}-`)
        const nested = jsonToYaml(item, indent + 1)
        lines.push(nested)
      } else {
        lines.push(`${spaces}- ${formatYamlValue(item)}`)
      }
    }
  } else if (typeof obj === "object" && obj !== null) {
    for (const [key, value] of Object.entries(obj)) {
      if (value === undefined) continue

      if (typeof value === "object" && value !== null) {
        if (Array.isArray(value) && value.length === 0) {
          lines.push(`${spaces}${key}: []`)
        } else if (!Array.isArray(value) && Object.keys(value).length === 0) {
          lines.push(`${spaces}${key}: {}`)
        } else {
          lines.push(`${spaces}${key}:`)
          lines.push(jsonToYaml(value, indent + 1))
        }
      } else {
        lines.push(`${spaces}${key}: ${formatYamlValue(value)}`)
      }
    }
  }

  return lines.join("\n")
}

function formatYamlValue(value: any): string {
  if (value === null) return "null"
  if (value === true) return "true"
  if (value === false) return "false"
  if (typeof value === "number") return String(value)
  if (typeof value === "string") {
    // Quote strings that need it
    if (value === "" || /[:#{}[\],&*!|>'"%@`]/.test(value) || /^\s|\s$/.test(value)) {
      return `"${value.replace(/"/g, '\\"')}"`
    }
    return value
  }
  return String(value)
}

export default openapiCommand
